// ui.theme/Color.kt
package com.niki914.breeno.cb.theme

import androidx.compose.ui.graphics.Color

// 定义你自己的颜色
// 例如，你可以从 Material Design 3 调色板工具中选择
val primaryLight = Color(0xFF6750A4)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADDFF)
val onPrimaryContainerLight = Color(0xFF21005D)
val secondaryLight = Color(0xFF625B71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8DEF8)
val onSecondaryContainerLight = Color(0xFF1D192B)
val tertiaryLight = Color(0xFF7D5260)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8E4)
val onTertiaryContainerLight = Color(0xFF31111D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1C1B1F)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1C1B1F)
val surfaceVariantLight = Color(0xFFE7E0EC)
val onSurfaceVariantLight = Color(0xFF49454F)
val outlineLight = Color(0xFF7A757F)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313034)
val inverseOnSurfaceLight = Color(0xFFF4EFF4)
val inversePrimaryLight = Color(0xFFD0BCFF)
val surfaceDimLight = Color(0xFFDED8E2)
val surfaceBrightLight = Color(0xFFFCF8FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F2FA)
val surfaceContainerLight = Color(0xFFF2ECF4)
val surfaceContainerHighLight = Color(0xFFECE6EF)
val surfaceContainerHighestLight = Color(0xFFE6E0EB)


val primaryDark = Color(0xFFD0BCFF)
val onPrimaryDark = Color(0xFF381E72)
val primaryContainerDark = Color(0xFF4F378B)
val onPrimaryContainerDark = Color(0xFFEADDFF)
val secondaryDark = Color(0xFFCCC2DC)
val onSecondaryDark = Color(0xFF332D41)
val secondaryContainerDark = Color(0xFF4A4458)
val onSecondaryContainerDark = Color(0xFFE8DEF8)
val tertiaryDark = Color(0xFFEFB8C8)
val onTertiaryDark = Color(0xFF492532)
val tertiaryContainerDark = Color(0xFF633B48)
val onTertiaryContainerDark = Color(0xFFFFD8E4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1C1B1F)
val onBackgroundDark = Color(0xFFE6E1E5)
val surfaceDark = Color(0xFF1C1B1F)
val onSurfaceDark = Color(0xFFE6E1E5)
val surfaceVariantDark = Color(0xFF49454F)
val onSurfaceVariantDark = Color(0xFFCCC4D4)
val outlineDark = Color(0xFF948F99)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E5)
val inverseOnSurfaceDark = Color(0xFF313034)
val inversePrimaryDark = Color(0xFF6750A4)
val surfaceDimDark = Color(0xFF1C1B1F)
val surfaceBrightDark = Color(0xFF38353B)
val surfaceContainerLowestDark = Color(0xFF121014)
val surfaceContainerLowDark = Color(0xFF201E23)
val surfaceContainerDark = Color(0xFF242227)
val surfaceContainerHighDark = Color(0xFF2F2D32)
val surfaceContainerHighestDark = Color(0xFF3A383D)